---
- hosts: all
  gather_facts: no
  become: yes
  vars:
    change_password: ChangeMeNow! # override with -e option
    # TODO: set this dynamically, so each user gets a unique password
  tasks:
    - name: Fetch non-system users
      shell: "awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd"
      register: users
      changed_when: false

    - name: Set the same password for all non-system users
      user:
        name: "{{ item }}"
        update_password: always
        password: "{{ change_password | password_hash('sha512') }}"
      with_items: "{{ users.stdout_lines }}"
      when: users.stdout_lines is defined and users.stdout_lines | length > 0

    # TODO: consider ssh keys in ~/.ssh/authorized_keys
