---
- hosts: all
  gather_facts: no
  become: yes
  vars:
    change_password: ChangeMeNow! # override with -e option
    change_sshkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBznwIb7wGsPVKqUqehpBK7wpUBHaiqU1HQEwfc48LzP
    # TODO: set this dynamically, so each user gets a unique password
  tasks:
    - name: Fetch non-system users
      shell: "awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd"
      register: users
      changed_when: false

    # Set the same password for all non-system users
    - name: Set the same password for all non-system users
      user:
        name: "{{ item }}"
        update_password: always
        password: "{{ change_password | password_hash('sha512') }}"
      with_items: "{{ users.stdout_lines }}"
      when: users.stdout_lines is defined and users.stdout_lines | length > 0

    # Force changing password on next login
    - name: Force Password Expiration
      command: "chage -d 0 {{ item }}"
      when: users.stdout_lines is defined and users.stdout_lines | length > 0
      with_items: "{{ users.stdout_lines }}"

    # Ensure existence of ~/.ssh/authorized_keys
    - name: Ensure user has /home/<user>/.ssh/authorized_keys
      stat:
        path: "/home/{{ item }}/.ssh/authorized_keys"
      register: auth_key_stat
      with_items: "{{ users.stdout_lines }}"
      when: users.stdout_lines is defined and users.stdout_lines | length > 0

    # Back up existing authorized_keys file
    - name: Backup existing authorized_keys file to authorized_keys.old
      copy:
        src: "/home/{{ item.item }}/.ssh/authorized_keys"
        dest: "/home/{{ item.item }}/.ssh/authorized_keys.old"
        remote_src: yes
        owner: "{{ item.item }}"
        group: "{{ item.item }}"
        mode: preserve
      register: backup
      with_items: "{{ auth_key_stat.results }}"
      when: "item.stat.exists"
    
    # Replace authorized_key file with our own
    - name: Replace content of authorized_keys file with a new SSH key
      copy:
        dest: "/home/{{ item.item }}/.ssh/authorized_keys"
        content: "{{ change_sshkey }}"
        owner: "{{ item.item }}"
        group: "{{ item.item }}"
        mode: '0600'
      with_items: "{{ auth_key_stat.results }}"
      when: "item.stat.exists and backup is defined"